### ISSUE TITLE
Default show.html.erb has post instead of @post

### ISSUE THREAD

**Issue by ishields** [acentro/picco_blog#8]
Not sure if the image was a recent change but wanted to point out that in the default show.html.erb view there is a typo post instead of @post.  As a result an error is thrown

![image](https://user-images.githubusercontent.com/3834864/62009586-ffd0d980-b12e-11e9-8489-5b5e8a0bfb56.png)

**Comment by brandonbango** [comment]
@ishields thanks for letting me know. I'll take a look at it and get it fixed.
