### ISSUE TITLE
Make official Release?

### ISSUE THREAD

**Issue by ishields** [acentro/picco_blog#9]
Hello! Does it make sense to make an official release of this gem?  That way any future commits going on in master won't automatically get released.

**Comment by brandonbango** [comment]
Hi @ishields, PiccoBlog 1.4.1 was released on RubyGems earlier this year. 

https://rubygems.org/gems/picco_blog/versions/1.4.1

**Comment by brandonbango** [comment]
PiccoBlog 1.4.2 has been released with the issue #8 fix.

https://rubygems.org/gems/picco_blog/versions/1.4.2

Thanks
